import { z } from "zod";
import { observablesSchema } from "./observables.schema.js";
import { vitalsSchema } from "./vitals.schema.js";
import { riskSchema } from "./risk.schema.js";

/**
 * Doctor brief schema — the final output of the HygieiaCore pipeline.
 *
 * DESIGN RULE: This is template-filled by Agent 3 pure code.
 * It is NOT free-form LLM prose. The template lives in:
 *   services/aegis-core/src/templates/doctor-brief.template.js
 *
 * The doctor should be able to read this in under 10 seconds:
 *   1. Chief complaint
 *   2. Flagged vitals
 *   3. Risk level + flags
 *   4. Recommended actions (from pre-validated protocol lookup)
 */
export const doctorBriefSchema = z.object({
  // --- Operational & Tracking Layer ---
  triageId: z.string().regex(/^[A-Z]+-\d+$/),

  // Maps to PulseOps/WardOps physical locations
  assignedLocation: z
    .string()
    .describe(
      "e.g., 'Resuscitation Bay 1', 'Waiting Room Chair 12', 'Ambulance Inbound'"
    ),

  // --- Core Patient Context ---
  patientDemographics: z.object({
    age: z.number().int().min(0).max(125),
    biologicalSex: z.enum(["MALE", "FEMALE", "UNKNOWN"]),
    preferredName: z.string().optional()
  }),

  // --- Clinical Inputs & Timing ---
  // Pure raw text from the citizen web app before AI formatting
  verbatimChiefComplaint: z
    .string()
    .describe("The exact unedited words from the patient/bystander"),

  // Critical for stroke (FAST), heart attack (STEMI), or sepsis protocol windows
  hoursSinceOnset: z
    .number()
    .min(0)
    .describe("Estimated hours since symptoms first started"),

  // --- Automated / AI Generated Insights Layer ---
  // Crisp 1-2 sentence overview generated by Agent 2
  summary: z
    .string()
    .describe("High-density clinical summary of presentation context"),

  observables: observablesSchema,
  vitals: vitalsSchema,
  risk: riskSchema,

  // --- Actionable Directives ---
  // Concrete clinical steps (e.g., "Establish large-bore IV", "Order STAT EKG", "Keep NPO")
  recommendations: z.array(z.string()).max(10),

  // --- Temporal / Validation Integrity ---
  generatedAt: z.string().datetime({
    message: "Must be a valid ISO 8601 UTC datetime string"
  })
});
