export const MOCK_PATIENT_BRIEF = {
    id: 'LION-4821',
    triageId: 'LION-4821',
    patientName: 'James Wilson',
    patientAge: 68,
    biologicalSex: 'MALE',
    assignedLocation: 'Resuscitation Bay 1',

    // Chief complaint and timing
    verbatimChiefComplaint: 'Respiratory distress with cyanosis and chest tightness. Senior adult, conscious on arrival.',
    hoursSinceOnset: 0.5,

    // Summary generated by AI
    summary: 'Senior adult with acute respiratory compromise and chest tightness on arrival.',

    // Pre-arrival observables (read-only)
    observables: [
        'DIFFICULTY_BREATHING',
        'CHEST_TIGHTNESS',
        'BLUISH_LIPS',
    ],

    esiLevel: 2,
    esiClassification: 'High risk — ER required',

    // Agent 3 Risk Flags
    riskFlags: [
        { severity: 'critical', message: 'SpO₂ 91% — below threshold (94%). Possible hypoxemia.' },
        { severity: 'critical', message: 'HR 112 bpm — tachycardia.' },
        { severity: 'warning', message: 'Immediate clinical assessment required.' },
    ],

    // Vitals (nurse-entered on arrival)
    vitals: {
        spo2: 91,
        heartRate: 112,
        systolicBP: 148,
        diastolicBP: 94,
        temperature: 98.8,
    },

    // Recommended actions
    recommendations: [
        'Initiate supplemental O₂. Target SpO₂ ≥ 94%.',
        'Obtain 12-lead ECG — rule out cardiac cause.',
        'IV access. Draw CBC, BMP, troponin, BNP.',
        'Escalate to attending physician.',
    ],

    // Protocol matching
    protocolMatch: {
        protocol: 'Respiratory Distress Protocol §4.2',
        indication: 'Hypoxemia, Adult',
        snomedCodes: ['271825005', '3415004', '29857009'],
    },

    // Agent confidence
    agentConfidence: {
        level: 'High',
        agreementCount: 3,
        totalAgents: 3,
    },

    generatedAt: new Date().toISOString(),
};

export const MOCK_AGENT_TRACE = `[10:52] Agent 1 · Context grounder
Input: "difficulty breathing, chest tightness, bluish lips"
→ ESI v4 match: Level 2 — High Risk
→ SNOMED: 271825005 (respiratory distress), 3415004 (cyanosis)
→ Routing: ER required (not urgent care)
→ First-aid: AHA BLS lookup [sit_upright, loosen_clothing, no_food_water]

[11:06] Agent 2 · Feature extractor
Input: nurse vital entry "spo2 91, hr 112, bp 148/94, temp 98.8"
→ Parsed: {SpO2: 91, HR: 112, BPsys: 148, BPdia: 94, Temp: 98.8}
→ Zod schema: PASS — all fields typed correctly
→ FHIR Observation resources created with LOINC codes

[11:06] Agent 3 · Deterministic gatekeeper (pure code — no LLM)
→ ALERT: SpO2 91% < threshold 94% → FLAG: hypoxemia_risk
→ ALERT: HR 112 > threshold 100 → FLAG: tachycardia
→ BP 148/94: elevated but below crisis threshold
→ Temp 98.8°F: within normal range
→ Doctor brief generated: template-filled, zero LLM involvement
→ FHIR Encounter priority: STAT
→ surge_index_score: 83% > 80% threshold → WardOps alert triggered`;

export const MOCK_TIMELINE = [
    {
        time: '10:52 pm',
        event: 'PulseTriage entry',
        type: 'Symptoms entered by relative. Token LION-4821 generated. 45-min TTL started.',
    },
    {
        time: '10:52 pm',
        event: 'AegisCore — ESI Level 2',
        type: "Routed to St. Mary's ER. Soft reservation placed. First-aid sent to Sarah's device.",
    },
    {
        time: '10:53 pm',
        event: 'Pre-arrival record pushed',
        type: 'LION-4821 appeared in PulseOps queue. Nurse Priya notified.',
    },
    {
        time: '11:04 pm',
        event: 'WardOps surge card fired',
        type: 'surge_index_score hit 83%. Coordinator notified via Teams Adaptive Card.',
    },
    {
        time: '11:06 pm',
        event: 'Patient arrived — vitals entered',
        type: 'QR scanned. Nurse Priya entered clinical measurements. Agent 3 ran gatekeeper check.',
    },
    {
        time: '11:08 pm',
        event: 'Doctor reviewing brief',
        type: 'Dr. Anand opened record. Bed 4B confirmed by coordinator via WardOps.',
    },
];